CREATE PROCEDURE DIM_PATIENT_FILTER_1
AS
	BEGIN TRY
			--GET A LIST OF ALL PATIENTS IN THE DW @DWPATIENTLIST
			--GET ALL PATIENTS FROM THE SOURCE DB WHERE NOT IN @DWPATIENTLIST
			
			
		  --ANY ERRORS GOES INTO THE ERROR TABLE
			INSERT INTO ETL_LOG ( SOURCE_PROCEDURE, ETL_EVENT_DATETIME, EVENT_DETAILS) 
			VALUES (@SOURCE_PROC, @ETL_EVE_DATE, @ETL_EVE_DET);
	END TRY
	BEGIN CATCH
			--IF THERE IS AN ERROR THROW IN TO THE LOG TABLE

	END CATCH

END