--///Ben Gardiner 102151272

-- Northen Hospital Database DDL

drop table IF EXISTS DIMSTAFF;
drop table IF EXISTS DIMTREATMENT;
drop table IF EXISTS DIMPATIENT;
drop table IF EXISTS DIMEASUREMENT;
drop table IF EXISTS DWEPISODE;
drop table IF EXISTS DWINTERVENTION;
drop table IF EXISTS DWTREATING;

CREATE TABLE DIMSTAFF(
	DWDIM_STAFFID INT IDENTITY(1,1) NOT NULL, 
	DWDIM_SOURCEID INT NOT NULL, 
	DWDIM_SOURCETABLE INT NOT NULL, 
	STAFFTYPE NVARCHAR(50) NOT NULL

	CONSTRAINT PK_DIMSTAFF PRIMARY KEY (DWDIM_STAFFID),
);


CREATE TABLE DIMTREATMENT(
	DWDIM_TREATMENTID INT IDENTITY(1,1) NOT NULL,  
	DWDIM_SOURCEID INT NOT NULL, 
	DWDIM_SOURCETABLE NVARCHAR(50) NOT NULL,
	RECORDTYPE NVARCHAR(50) NOT NULL, 
	CATEGORY NVARCHAR(50) NOT NULL

	CONSTRAINT PK_DIMTREATMENT PRIMARY KEY (DWDIM_TREATMENTID),
);

CREATE TABLE DIMPATIENT(
	DWDIM_TREATMENTID INT IDENTITY(1,1) NOT NULL,
	DWDIM_SOURCEID INT NOT NULL, 
	DWDIM_SOURCETABLE NVARCHAR(50) NOT NULL, 
	GENDER NVARCHAR(50) NOT NULL,
	YEAROFBIRTH INT NOT NULL,
	SUBURB NVARCHAR(50) NOT NULL,
	POSTCODE NVARCHAR(4) NOT NULL,
	COUNTRYOFBIRTH NVARCHAR(50) NOT NULL,
	PREFERREDLANGUAGE NVARCHAR(50) NOT NULL,
	LIVESALONE BIT NOT NULL,
	ACTIVE BIT NOT NULL,
	DIAGNOSIS NVARCHAR(500) NULL,
	CATEGORYNAME NVARCHAR(50) NOT NULL,
	PROCEDUREDATE DATETIME NULL

	CONSTRAINT PK_DIMTREATMENT PRIMARY KEY (DWDIM_TREATMENTID),
);


CREATE TABLE DIMEASUREMENT(
	DWDIM_MEASUREMENTID INT IDENTITY(1,1) NOT NULL,
	DWDIM_SOURCETABLE NVARCHAR(50) NULL,
	MEASUREMENTID INT NOT NULL,
	MEASUREMENTNAME NVARCHAR(50) NOT NULL,
	DATAPOINTNUMBER INT NOT NULL,
	UPPERLIMIT INT NOT NULL,
	LOWERLIMIT INT NOT NULL,
	[NAME] NVARCHAR(50)
	CONSTRAINT PK_DIMTREATMENT PRIMARY KEY (DWDIM_MEASUREMENTID),
);

CREATE TABLE DWEPISODE(
	DWFACT_EPISODEID INT IDENTITY(1,1) NOT NULL,
	DWFACT_EPISODEDATEID INT NOT NULL,
	DATETIMERECORDED DATETIME NOT NULL,
	FREQUENCYSETDATE DATETIME NOT NULL,
	FREQUENCY INT NOT NULL,
	[VALUE] FLOAT NOT NULL,
	CONSTRAINT PK_FACTEPISODE PRIMARY KEY (DWFACT_EPISODEID),
);

CREATE TABLE DWINTERVENTION(
	DWFACT_INTERVENTIONID INT IDENTITY(1,1) NOT NULL,
	DWDATE_INTERVENTIONDATEID INT NOT NULL,
	DWDIM_PATIENTID INT NOT NULL,
	DWDIM_TREATMENTID INT,
	NOTES NVARCHAR(MAX), 
	CONSTRAINT PK_FACTINTERVENTION PRIMARY KEY (DWFACT_INTERVENTIONID),
);

CREATE TABLE DWTREATING(
	DWFACT_TREATINGID INT IDENTITY(1,1) NOT NULL,
	DWDIM_STAFFID INT NOT NULL,
	DWDIM_PATIENTID INT NOT NULL,
	DWDATE_STARTDATE INT NOT NULL,
	DWDATE_ENDDATE INT NULL
	CONSTRAINT PK_FACTTREATING PRIMARY KEY (DWFACT_TREATINGID),
);

CREATE TABLE DWDATE(   
	DATEKEY INTEGER PRIMARY KEY, 
    DATEVALUE DATE,
    DAYOFMONTH INTEGER, -- FIELD WILL HOLD DAY NUMBER OF MONTH
    DAYSUFFIX NVARCHAR(2), -- APPLY SUFFIX AS 1ST, 2ND ,3RD ETC
    DAYNAME NVARCHAR(9), -- CONTAINS NAME OF THE DAY, SUNDAY, MONDAY 
    DAYSHORTNAME NVARCHAR(3), -- DAY SHOORT NAME EG MON, TUE
	DAYOFWEEK INTEGER,-- FIRST DAY SUNDAY=1 AND SATURDAY=7
    DAYOFQUARTER INTEGER,
    DAYOFYEAR INTEGER,
    WEEKOFYEAR INTEGER,--WEEK NUMBER OF THE YEAR
    MONTHOFYEAR INTEGER, --NUMBER OF THE MONTH 1 TO 12
    MONTHNAME NVARCHAR(9),--JANUARY, FEBRUARY ETC
    MONTHSHORTNAME NVARCHAR(3), -- JAN FEB, MAR ETC
	MONTHOFQUARTER INTEGER,-- MONTH NUMBER BELONGS TO QUARTER
    QUARTER INTEGER,
    QUARTERNAME NVARCHAR(6),--FIRST,SECOND..
    YEAR INTEGER,-- YEAR VALUE OF DATE STORED IN ROW
    FIRSTDAYOFMONTH DATE,
    LASTDAYOFMONTH DATE,
    FIRSTDAYOFQUARTER DATE,
    LASTDAYOFQUARTER DATE,
    FIRSTDAYOFYEAR DATE,
    LASTDAYOFYEAR DATE,
    ISWEEKDAY INTEGER-- 0=WEEK END ,1=WEEK DAY
);

