--//CREATE THE TABLE DATA TYPE 
DROP TYPE IF EXISTS DEMOTABLETYPE
CREATE TYPE DEMOTABLETYPE AS TABLE
(
	URNNUMBER NVARCHAR(100),
	EMAIL NVARCHAR(256),
	TITLE NVARCHAR(100)
);

GO

BEGIN

DECLARE @PATIENTTABLE DEMOTABLETYPE;
INSERT INTO @PATIENTTABLE
SELECT URNNUMBER, EMAIL, TITLE
FROM PATIENT;

SELECT * FROM @PATIENTTABLE
END
