USE NHDW
DROP PROCEDURE IF EXISTS ETL_FILTER_PROCESS_PATIENT;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE ETL_FILTER_PROCESS_PATIENT  @DATA TestPatientTable READONLY AS
BEGIN
    BEGIN TRY

     --Select d.CategoryName from (SELECT * FROM @DATA) d;

	-- FILTER YEAR
	-- SELECT * FROM @DATA
	-- WHERE YEAR.LEN

	--FILTER GENDER
	--SELECT * FROM @DATA
	--WHERE Gender NOT IN ('Male', 'Female')

  
	--INSERT INTO ERROREVENT(ERRORID, SOURCE_ID, SOURCE_TABLE, FILTERID, [DATE_TIME], [ACTION], NOTES) 
	--SELECT 'NHRM', Dt.DWDIM_SOURCEID, 'PATIENT', 1, (SELECT SYSDATETIME()), 'MODIFY', 'misspleled gender' 
	--FROM @DATA Dt
	--WHERE dt.Gender NOT IN ('Male', 'Female');

	--INSERT INTO ERROREVENT(ERRORID, SOURCE_ID, SOURCE_TABLE, FILTERID, [DATE_TIME], [ACTION], NOTES) 
	--SELECT 'NHRM', Dt.DWDIM_SOURCEID, 'PATIENT', 2, (SELECT SYSDATETIME()), 'SKIP', 'wrong year lwength' 
	--FROM @DATA Dt
	--WHERE LEN(dt.YEAROFBIRTH) != 4;

	INSERT INTO ERROREVENT( SOURCE_DB, SOURCE_ID, SOURCE_TABLE, FILTERID, [DATE_TIME], [ACTION], NOTES) 
	SELECT 'NHRM', Dt.DWDIM_SOURCEID, 'PATIENT', 3, (SELECT SYSDATETIME()), 'SKIP', 'Category Name is null and requires investigaton' 
	FROM @DATA Dt
	WHERE dt.CategoryName IS NULL;

	--Select CategoryName
	--from @DATA
	
	select * from ERROREVENT
	
 
    END TRY
    BEGIN CATCH
      
    --   IF ERROR_NUMBER() IN (50290, 50300)
    --   THROW;
      
    --   BEGIN
    --       DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
    --       THROW 50000 , @ERRORMESSAGE , 1
    --   END
    END CATCH
END