USE NHDW
DROP PROCEDURE IF EXISTS ETL_FILTER_PROCESS_MEASUREMENT;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE ETL_FILTER_PROCESS_MEASUREMENT  @DATA TESTMEASUREMENTTABLE READONLY AS
BEGIN
    BEGIN TRY


	INSERT INTO ERROREVENT( SOURCE_DB, SOURCE_ID, SOURCE_TABLE, FILTERID, [DATE_TIME], [ACTION], NOTES) 
	SELECT 'NHRM', Dt.DWDIM_SOURCEID, 'MEASUREMENT', 3, (SELECT SYSDATETIME()), 'SKIP', 'Category Name is null and requires investigaton' 
	FROM @DATA Dt
	WHERE dt.MEAUREMENTID IS NULL;

	--Select CategoryName
	--from @DATA
	
	select * from ERROREVENT
	
 
    END TRY
    BEGIN CATCH
      
    --   IF ERROR_NUMBER() IN (50290, 50300)
    --   THROW;
      
    --   BEGIN
    --       DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
    --       THROW 50000 , @ERRORMESSAGE , 1
    --   END
    END CATCH
END